### ISSUE TITLE
Plusieurs bugs affectent MPE

### ISSUE THREAD

**Issue by d-courtine** [meb-team/MetaPathExplorer#1]
Bonjour Corentin,

Je me suis plongé dans le code de MetaPathExplorer car j'avais besoin d'un outil pour afficher rapidement les cartes KEGG avec les KO annotés dans mes données. Cependant je n'ai jamais réussi à refaire tourner MPE jusqu'au bout, même sur l'exemple fourni.
J'utilise la version _master_ [#54da590](https://github.com/meb-team/MetaPathExplorer/commit/54da590973526b7c25109a6952a7e52e5177a0e0). 

- [x] #2
En modifiant cette boucle, `for(my $i=1;$i<$#line;$i++){` par `for(my $i=1;$i<=$#line;$i++){` le problème est résolu.

- [x] #3
Si j'ai le temps, j'apporterai toutes ces modifications à MPE.

- [x] #4

Cette issue est simplement là pour garder une traces des couacs que j'ai pu observer

Damien, IE bioinfo, MEB

**Comment by chochart** [comment]
Bonjour Damien, 

Merci pour tes commentaires. J'ai séparé tes différentes remontées dans des issues différentes. Le point 3 était déjà réglé localement. Pour le point 2, j'avais noté le soucis, dès que j'ai le temps je m'y penche en détail mais ça ne devrait pas être compliqué. 

Corentin
